### ISSUE TITLE
Initial project feedback

### ISSUE THREAD

**Issue by thedarkjester** [cryptobynight/blockchain-developer-bootcamp-final-project#1]
The minting and CSS is pretty interesting, and works well. 

Some tips and optimisations:

1. SafeMath is not needed as of 0.8.0 as over/underflows revert by default
2. Libraries can be deployed/linked if reused else for other projects - saves gas per project
3. Struct initialisation can be improved to use a default and then assign values
```
StructName struct1;
struct1.PropertyName= PropertyValue;
```
4. inter-contract execution doesn't really apply to "ownable" as it is inherited and embedded in your contract. It is more a case of call something ( `address(addr).delegatecall...` )

**Comment by cryptobynight** [comment]
Thanks for the feedback. 

1. I know SafeMath is not technically needed, but I wanted the practice in building the functionality myself and implementing.
2. Great tip - thanks.
3. Are you referring to lines 41-44 of the Diamonds contract?
4. I'm not sure I'm following. Can you extrapolate?

Final question as I'm new to Github and coding in general. Do I need to make these changes now and/or resolve/close this issue to pass my final project?

**Comment by thedarkjester** [comment]
1. Cool - saves gas not using it, but good to know how it works +1
2. np
3. Correct - I know this is two values, but I made note of it for general practice. 
4. When you inherit Ownable, it effectively makes it part of your contract when compiling. The inter-contract execution module in the course discusses `.call` and the  `.deletegatecall` uses and how that changes things. Inter-contract calling is if you are executing code on a separately deployed contract vs. all in your current one.

**Comment by cryptobynight** [comment]
3. Ok thanks - understood.
4. Ok great, thanks. I did go through the inter-contract execution module but I probably need to go through that again. Definitely still learning and I will take another read through.

I'm not sure you saw my final question in my last comment regarding resolving/closing issues to pass the project. Are these comments to be implemented at a future date or do I need to make them now?

**Comment by thedarkjester** [comment]
I will close the issue, it was just a way to give feedback. You don't have to implement it, this is only extra tips for the future.
